#! /bin/bash
# build OOoSVN from SVN
rm -rf build
mkdir build
cd extension
7za a -tzip -mfb=258 -mpass=15 ../build/ooosvn-0.3.3.zip ./*
cd ..
cp shellscripts/* build
cp gpl.txt build
cp readme.txt build
cd build
7za a -tzip -mfb=258 -mpass=15 ../ooosvn-beta-0.3.3.zip ./*