#! /bin/bash
# build OOoSVN from sourcefiles, as structured in SVN repo
# Usage: sh buildscript [version]
# eg.    sh buildscript 0.3.4

rm -rf build
mkdir build

cd extension
zip -rDX ../build/ooosvn-$1.zip * -x *.svn*
#7za a -tzip -mfb=258 -mpass=15 ../build/ooosvn-0.3.3.zip ./*

cd ..
cp shellscripts/* build
cp gpl.txt build
cp readme.txt build

cd build
zip -rDX ../ooosvn-beta-$1.zip * -x *.svn*
#7za a -tzip -mfb=258 -mpass=15 ../ooosvn-beta-0.3.3.zip ./*
cd ..
rm -rf build